# Generated by Django 5.0.4 on 2024-04-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_user_email_active_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active_code',
        ),
    ]
